#!/usr/bin/env python3
"""Script to backup (pull) GitHub repositories to a (non-bare) local copy."""

import copy
import dataclasses
import logging
import logging.config
import pathlib
import subprocess
import sys
import typing
import time

__version__ = "2024.3.19"

# logging configuration
LogConfigType = dict[str, typing.Union[typing.Any, dict[str, typing.Union[typing.Any, dict[str, typing.Any]]]]]
LOG_CONFIG: LogConfigType = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(asctime)s.%(msecs)03d %(levelname)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "precise": {
            "format": "%(asctime)s.%(msecs)03d %(levelname)s [%(name)s.%(funcName)s(%(lineno)d)] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
            "stream": "ext://sys.stdout",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": "DEBUG",
            "formatter": "precise",
            "filename": "application.log",
            "when": "W6",
            "backupCount": 1,
        },
    },
    "root": {"level": "INFO", "handlers": ["console", "file"]},
}


@dataclasses.dataclass
class Settings:
    """Class for settings"""

    executable: str = ""
    debug: bool = False
    prompt: bool = True
    folders: list[str] = dataclasses.field(default_factory=list)


def parse_args(argv: list[str]) -> Settings:
    """Parse command line arguments.

    Args:
        argv (list[str]): all command line arguments

    Returns:
        Settings: configuration from defaults and arguments
    """
    settings = Settings()
    settings.executable = argv[0]
    for arg in argv[1:]:
        match arg.lower():
            case "-d" | "--debug":
                settings.debug = True
            case "--noprompt":
                settings.prompt = False
            case _:
                settings.folders.append(arg)

    if not settings.folders:
        settings.folders = ["."]

    return settings


def execute_cmd(
    args: list[str],
    cwd: None | str | pathlib.Path = None,
    callback: None | typing.Callable = None,
    rstrip: bool = True,
) -> tuple[int, str]:
    """Call an external program (synchronously) as a subprocess.

    This method can be used either in a normal or in a streaming mode: when
    the `callback` argument is a callable it runs in streaming mode.

    The normal mode works as might be expected: spawn an external process,
    wait for completion and return the returncode together with the output.

    The streaming mode works by starting an external process, read its output
    (line by a line) and call a callback method for each line (while the
    external process is still active). After the process completes, only the
    returncode is returned without the output. The callback method receives
    a line of output as its only argument, e.g. will be called as:
        callback(line_of_output)

    For convenience: by default the `str.rstrip()` method is applied to the
    output (normal mode: entire output, streaming mode: on each line) to strip
    white space and line endings (`\n`) at the end of the output / each line.
    If you don't want this you can set the `rstrip` argument to `False`.

    Note: there is no separation between `stdout` and `stderr`; both are
    always combined.

    Args:
        args (list[str]): command and its arguments to be executed,
            e.g. ["python", "-c", "print('Hello World')"]
        cwd (None | str | pathlib.Path, optional): working directory, the
            external process runs in this directory.
        callback (None | typing.Callable, optional): optional callback method,
            if this is not `None` it is called for each line of output
            generated by the external process.
        rstrip (bool, optional): apply the `str.rstrip()` to the output,
            either on the entire output (normal) or on a line by line
            basis (streaming).

    Returns:
        tuple[int, str]: (returncode, only_normal_output_otherwise_None)
            The second argument is only filled in normal mode with the
            output of the process; in streaming mode it is always "".
    """
    logger = logging.getLogger(__name__)
    logger.debug("executing: '%s'", " ".join(args))
    proc_args = {
        "args": args,
        "stdout": subprocess.PIPE,
        "stderr": subprocess.STDOUT,
        "text": True,
    }
    if cwd is not None:
        proc_args["cwd"] = cwd
        logger.debug("working directory set to: '%s'", cwd)

    # streaming mode
    if callable(callback):
        logger.debug("executing in streaming mode")
        with subprocess.Popen(**proc_args) as proc:
            line = proc.stdout.readline()  # type: ignore
            while line:
                callback(line.rstrip() if rstrip else line)
                line = proc.stdout.readline()  # type: ignore
        logger.debug("returncode: %d", proc.returncode)
        return proc.returncode, ""

    # normal mode
    logger.debug("executing in normal mode")
    proc_args["check"] = False  # do NOT throw an exception when rc != 0
    proc = subprocess.run(**proc_args)  # pylint: disable=subprocess-run-check
    logger.debug("returncode: %d", proc.returncode)
    return proc.returncode, proc.stdout.rstrip() if rstrip else proc.stdout


def pull_from_remote(repo_folder: pathlib.Path) -> int:
    """Pull remote (origin) repository.

    Args:
        repo_folder (pathlib.Path): folder with a repo having a remote origin

    Returns:
        int: 0=success, 1=error
    """
    logger = logging.getLogger(__name__)

    logger.info("pulling '%s'", repo_folder)
    git_pull_cmd = ["git", "pull", "--all", "--ff-only"]
    time_start = time.perf_counter()
    rc, _ = execute_cmd(git_pull_cmd, cwd=repo_folder, callback=lambda line: logger.info("  %s", line))
    time_end = time.perf_counter()

    logger.info("pull finished in %0.1f seconds", time_end - time_start)
    if rc != 0:
        logger.critical("returncode is %d, please check logs", rc)
        return 1
    return 0


def get_repo_remote_origin(repo_folder: pathlib.Path) -> str:
    """Check whether the repository has a remote origin.

    Args:
        repo_folder (pathlib.Path): repository (folder) to check

    Returns:
        str: remote origin
    """
    logger = logging.getLogger(__name__)

    git_remote_origin_cmd = ["git", "config", "--get", "remote.origin.url"]
    try:
        rc, git_remote_origin = execute_cmd(git_remote_origin_cmd, cwd=repo_folder)
    except Exception:  # pylint: disable=broad-exception-caught
        logger.exception("exception executing '%s'", " ".join(git_remote_origin_cmd))
        return ""

    if rc not in (0, 1):
        logger.error("error executing '%s', output:\n%s", " ".join(git_remote_origin_cmd), git_remote_origin)
        return ""
    if not git_remote_origin:
        logger.debug("no remote origin for '%s'", repo_folder)
        return ""
    logger.debug("remote origin for '%s': '%s'", repo_folder, git_remote_origin)
    return git_remote_origin


def folder_is_non_bare_git_repo(folder_name: str | pathlib.Path) -> bool:
    """Check if a folder is a (non-bare) Git repository.

    A folder qualifies as a Git repository if this file is present:
        .git/config

    Args:
        folder_name (str | pathlib.Path): folder to be checked

    Returns:
        bool: folder is a Git repository (True) or not (False)
    """
    logger = logging.getLogger(__name__)
    if len(list(pathlib.Path(folder_name).glob(".git/config"))) == 1:
        logger.debug("found a Git repository: '%s'", folder_name)
        return True

    logger.debug("not a non-bare Git repository: '%s'", folder_name)
    return False


def get_repos_in_folder(folder: str | pathlib.Path) -> typing.Iterator[pathlib.Path]:
    """Get Git repositories (directories) in a folder.

    Args:
        folder (str | pathlib.Path): main folder, sub folders may or may
            not be repositories

    Returns:
        typing.Iterator[pathlib.Path]: directories with Git repositories

    Yields:
        Iterator[typing.Iterator[pathlib.Path]]: Git repository folder(s)
    """
    logger = logging.getLogger(__name__)
    folder_path = pathlib.Path(folder)
    if folder_path.is_dir():
        logger.debug("'%s' is a folder, enumerating children", folder_path)
        for child in folder_path.iterdir():
            if child.is_dir() and folder_is_non_bare_git_repo(child):
                yield child
    else:
        logger.warning("'%s' is not a folder", folder_path)


def git_found() -> bool:
    """Check whether git is callable.

    Git should be in the path.

    Returns:
        bool: git is callable (True) or not (False)
    """
    logger = logging.getLogger(__name__)

    git_version_cmd = ["git", "--version"]
    try:
        rc, git_version = execute_cmd(git_version_cmd)
    except Exception:  # pylint: disable=broad-exception-caught
        logger.exception("exception executing '%s'", " ".join(git_version_cmd))
        return False

    if (rc != 0) or ("git version" not in git_version):
        logger.debug("output of '%s' is unexpected (rc=%d):\n%s", " ".join(git_version_cmd), rc, git_version)
        return False

    logger.debug("found Git: %s", git_version)
    return True


def process_folders(folders: list[str]) -> int:
    """Process all folders (do the work).

    Args:
        folders (list[str]): folders to be processed

    Returns:
        int: number of errors (0=no errors)
    """
    logger = logging.getLogger(__name__)
    num_errors = 0
    for folder in folders:
        logger.info("processing folder '%s'", folder)
        for repo_folder in get_repos_in_folder(folder):
            if get_repo_remote_origin(repo_folder):
                num_errors += pull_from_remote(repo_folder)

    return num_errors


def main(settings: Settings) -> int:
    """Main function.

    Args:
        settings (Settings): settings from command line

    Returns:
        int: exit status (to be used as returncode of the script):
            -1: git not found
            0: no errors
            >0: number of errors
    """
    script_name = pathlib.Path(settings.executable).stem
    log_config = copy.deepcopy(LOG_CONFIG)
    log_config["handlers"]["file"]["filename"] = pathlib.Path(".") / f"{script_name}.log"
    if settings.debug:
        log_config["root"]["level"] = "DEBUG"
    logging.config.dictConfig(log_config)

    logger = logging.getLogger(__name__)
    logger.info("starting '%s' V%s", pathlib.Path(sys.argv[0]).name, __version__)

    returncode = 0
    if git_found():
        try:
            returncode = process_folders(settings.folders)
        except Exception:  # pylint: disable=broad-except
            logger.critical("caught unhandled exception", exc_info=True)
            returncode = -1
    else:
        logger.critical("Git not found")
        returncode = -1

    logger.info("exit with returncode=%d", returncode)
    return returncode


if __name__ == "__main__":
    SETTINGS = parse_args(sys.argv)
    RETURNCODE = main(SETTINGS)
    if (RETURNCODE != 0) and SETTINGS.prompt:
        input(f"\n>>> Check logs (RC={RETURNCODE}), press <ENTER> to continue...")
    sys.exit(RETURNCODE)
